// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/app/components/widgets/AppLogo.vue')['default']
    Cookies: typeof import('./src/app/components/Cookies.vue')['default']
    Dummy: typeof import('./src/app/components/Dummy.vue')['default']
    HelloWorld: typeof import('./src/app/components/HelloWorld.vue')['default']
    Setup: typeof import('./src/app/components/Setup.vue')['default']
  }
}

export { }
