// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/playground/app/components/widgets/AppLogo.vue')['default']
    Content: typeof import('./src/playground/app/components/Content/Content.vue')['default']
    Cookies: typeof import('./src/playground/app/components/Cookies.vue')['default']
    Dummy: typeof import('./src/playground/app/components/Dummy.vue')['default']
    HelloWorld: typeof import('./src/playground/app/components/HelloWorld.vue')['default']
    Inner: typeof import('./src/playground/app/components/Right/Inner.vue')['default']
    Left: typeof import('./src/playground/app/components/Left/Left.vue')['default']
    Menu: typeof import('./src/playground/app/components/Menu/Menu.vue')['default']
    Right: typeof import('./src/playground/app/components/Right/Right.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setup: typeof import('./src/playground/app/components/Setup.vue')['default']
    Shared: typeof import('./src/playground/app/components/Shared/Shared.vue')['default']
  }
}
