// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/playground/app/components/widgets/AppLogo.vue')['default']
    Cookies: typeof import('./src/playground/app/components/Cookies.vue')['default']
    Dummy: typeof import('./src/playground/app/components/Dummy.vue')['default']
    HelloWorld: typeof import('./src/playground/app/components/HelloWorld.vue')['default']
    Inner: typeof import('./src/playground/app/components/Right/Inner.vue')['default']
    Left: typeof import('./src/playground/app/components/Left/Left.vue')['default']
    Right: typeof import('./src/playground/app/components/Right/Right.vue')['default']
    Setup: typeof import('./src/playground/app/components/Setup.vue')['default']
    Shared: typeof import('./src/playground/app/components/Shared/Shared.vue')['default']
  }
}

export { }
